version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postrgesql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planman
      - TZ=Europe/Amsterdam
      - PGTZ=Europe/Amsterdam
    ports:
      - "5432:5432"
  planman:
    container_name: planman
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db