version: "3.9"
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postrgesql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  planman:
    container_name: planman
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db